server:
  port: 8080
  servlet:
    context-path: /cold_server


#中文参数乱码解决
spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

#根据是生产还是开发切换配置文件
  profiles:
    active: prod


mybatis:
  #mapper.xml所在位置
  mapper-locations: classpath:mapping/*/*.xml
  #实体类所做包
  type-aliases-package: com.cck.model
  #数据库空字段也返回
  configuration:
    call-setters-on-nulls: true



myproperties:
  wjtFilePath: D:/token/
  arrayProps: 1,2,3,4,5

ymlmanager:
  mapProps:
    wjtFilePath: D:/token/
    key2: value2


